package com.thorium.launchbridge;

import android.accessibilityservice.AccessibilityService;
import android.accessibilityservice.AccessibilityServiceInfo;
import android.app.ActivityOptions;
import android.content.ComponentName;
import android.content.Intent;
import android.os.Handler;
import android.os.Looper;
import android.os.SystemClock;
import android.util.Log;
import android.view.KeyEvent;
import android.view.accessibility.AccessibilityEvent;
import android.view.accessibility.AccessibilityNodeInfo;

import java.util.List;

/**
 * Turns the Thor's dedicated Stop button into a universal "close content"
 * control.  The firmware exposes that physical button as BUTTON_SELECT.
 */
public final class StopButtonService extends AccessibilityService {
    private static final String TAG = "ThorStop";
    private static final String PEGASUS_PACKAGE = "org.pegasus_frontend.android";
    private static final String DOLPHIN_PACKAGE = "org.dolphinemu.dolphinemu";
    private static final String DOLPHIN_EXIT_ID =
            "org.dolphinemu.dolphinemu:id/menu_exit";
    private static final String PREVIEW_PACKAGE = "com.thorium.preview";
    private static final String PREVIEW_BLANK = "com.thorium.preview.BLANK";
    private static final long HOLD_TO_EXIT_MS = 1000L;
    private static final ComponentName PEGASUS_ACTIVITY = new ComponentName(
            PEGASUS_PACKAGE, "org.pegasus_frontend.android.MainActivity");

    private final Handler handler = new Handler(Looper.getMainLooper());
    private String upperPackage = PEGASUS_PACKAGE;
    private long lastStopAt;
    private boolean stopHeld;
    private boolean holdActionTriggered;
    private String pressedContentPackage = "";
    private long stopGeneration;

    @Override
    protected void onServiceConnected() {
        AccessibilityServiceInfo info = new AccessibilityServiceInfo();
        info.eventTypes = AccessibilityEvent.TYPE_WINDOW_STATE_CHANGED
                | AccessibilityEvent.TYPE_WINDOWS_CHANGED;
        info.feedbackType = AccessibilityServiceInfo.FEEDBACK_GENERIC;
        info.notificationTimeout = 0;
        info.flags = AccessibilityServiceInfo.FLAG_REQUEST_FILTER_KEY_EVENTS
                | AccessibilityServiceInfo.FLAG_RETRIEVE_INTERACTIVE_WINDOWS
                | AccessibilityServiceInfo.FLAG_INCLUDE_NOT_IMPORTANT_VIEWS
                | AccessibilityServiceInfo.FLAG_REPORT_VIEW_IDS;
        setServiceInfo(info);
    }

    @Override
    public void onAccessibilityEvent(AccessibilityEvent event) {
        if (event == null || event.getDisplayId() != 0 || event.getPackageName() == null)
            return;

        String packageName = event.getPackageName().toString();
        if (packageName.equals(PEGASUS_PACKAGE)) {
            // In the unified build Lucent and the accessibility service share
            // a package. Display 0 is still unambiguous because the preview
            // activity lives on the lower display and was filtered above.
            upperPackage = PEGASUS_PACKAGE;
        } else if (!packageName.equals(getPackageName())
                && !packageName.equals("com.android.systemui")
                && !packageName.equals(PREVIEW_PACKAGE)) {
            upperPackage = packageName;
        }
    }

    @Override
    protected boolean onKeyEvent(KeyEvent event) {
        int keyCode = event.getKeyCode();
        boolean isThorStop = keyCode == KeyEvent.KEYCODE_BUTTON_SELECT
                || keyCode == KeyEvent.KEYCODE_MEDIA_STOP;
        if (!isThorStop)
            return false;

        if (event.getAction() == KeyEvent.ACTION_UP) {
            boolean wasHeldAction = holdActionTriggered;
            String contentPackage = pressedContentPackage;
            stopHeld = false;
            holdActionTriggered = false;
            pressedContentPackage = "";
            ++stopGeneration;
            if (!PEGASUS_PACKAGE.equals(upperPackage)) {
                // A quick press is a global Lucent launcher. A completed hold
                // already performed the same return at the one-second mark.
                if (!wasHeldAction) returnToPegasus(contentPackage);
                return true;
            }
            // Inside Lucent itself the physical button remains Select.
            return false;
        }
        if (event.getAction() != KeyEvent.ACTION_DOWN)
            return false;

        // Repeated DOWN events are generated by Android after its normal key
        // repeat delay. They must remain visible to the emulator, but must not
        // restart the one-second hold timer.
        if (event.getRepeatCount() != 0)
            return !PEGASUS_PACKAGE.equals(upperPackage);

        // Window-change events on some Thor firmware builds omit their display
        // id. Resolve the active upper-screen package again at the exact key
        // press so a newly opened emulator can never be mistaken for Pegasus.
        AccessibilityNodeInfo activeRoot = getRootInActiveWindow();
        if (activeRoot != null && activeRoot.getPackageName() != null) {
            String activePackage = activeRoot.getPackageName().toString();
            if (activePackage.equals(PEGASUS_PACKAGE)) {
                upperPackage = PEGASUS_PACKAGE;
            } else if (!activePackage.equals(getPackageName())
                    && !activePackage.equals("com.android.systemui")
                    && !activePackage.equals(PREVIEW_PACKAGE)) {
                upperPackage = activePackage;
            }
        }

        // In Pegasus itself, this key is Select with no alternate action.
        if (PEGASUS_PACKAGE.equals(upperPackage))
            return false;
        final String contentPackage = upperPackage;
        stopHeld = true;
        holdActionTriggered = false;
        pressedContentPackage = contentPackage;
        final long generation = ++stopGeneration;
        handler.postDelayed(new Runnable() {
            @Override
            public void run() {
                if (!stopHeld || generation != stopGeneration)
                    return;
                long now = SystemClock.uptimeMillis();
                if (now - lastStopAt < HOLD_TO_EXIT_MS)
                    return;
                lastStopAt = now;
                stopHeld = false;
                holdActionTriggered = true;
                ++stopGeneration;
                // Background the live emulation task instead of terminating
                // it. Android delivers onPause/onStop so emulators can flush
                // battery saves and their own per-game autosave slot, while
                // the process remains immediately resumable until the OS
                // needs its memory. This is intentionally identical for
                // Dolphin and every standalone emulator.
                returnToPegasus(contentPackage);
            }
        }, HOLD_TO_EXIT_MS);
        // Outside Lucent consume both halves so a short global-launch press
        // cannot also trigger an emulator's Select action. Inside Lucent the
        // early return above keeps the button's native Select behavior.
        return true;
    }

    private void exitDolphinAndReturn() {
        // Dolphin exposes a real accessible Exit Emulation control. Invoke it
        // directly when its menu is already open; otherwise open the menu with
        // Back and click it on the next UI frame. This follows Dolphin's own
        // shutdown path, so its native emulation session and sole task finish
        // together instead of leaving a cached library task behind.
        blankPreview();
        if (clickDolphinExit()) {
            verifyNaturalDolphinReturn();
            return;
        }

        performGlobalAction(GLOBAL_ACTION_BACK);
        handler.postDelayed(new Runnable() {
            @Override
            public void run() {
                if (clickDolphinExit())
                    verifyNaturalDolphinReturn();
                else
                    fallbackToPegasusAfterDolphinExit(650L);
            }
        }, 70L);
    }

    /**
     * Dolphin's Exit Emulation action finishes its only activity. Android then
     * reveals the existing Pegasus task by itself. Starting Pegasus again in
     * this interval used to produce two resume/surface-creation passes a few
     * milliseconds apart. Qt could miss the resulting focus acknowledgement,
     * making the restored frontend appear frozen and restarting its import
     * scan. Let the normal task transition finish and launch only as a genuine
     * recovery path.
     */
    private void verifyNaturalDolphinReturn() {
        handler.postDelayed(new Runnable() {
            @Override
            public void run() {
                String activePackage = activePackage();
                if (PEGASUS_PACKAGE.equals(activePackage)) {
                    Log.i(TAG, "Dolphin exited; Pegasus resumed naturally");
                    return;
                }
                fallbackToPegasusAfterDolphinExit(750L);
            }
        }, 650L);
    }

    private void fallbackToPegasusAfterDolphinExit(long delayMillis) {
        handler.postDelayed(new Runnable() {
            @Override
            public void run() {
                String activePackage = activePackage();
                if (PEGASUS_PACKAGE.equals(activePackage)) {
                    Log.i(TAG, "Pegasus became active before fallback");
                    return;
                }
                Log.w(TAG, "Dolphin return did not reveal Pegasus; using fallback from "
                        + activePackage);
                returnToPegasus(null);
            }
        }, delayMillis);
    }

    private String activePackage() {
        AccessibilityNodeInfo root = getRootInActiveWindow();
        if (root != null && root.getPackageName() != null)
            return root.getPackageName().toString();
        return "";
    }

    private void blankPreview() {
        sendBroadcast(new Intent(PREVIEW_BLANK).setPackage(PREVIEW_PACKAGE));
    }

    private boolean clickDolphinExit() {
        AccessibilityNodeInfo root = getRootInActiveWindow();
        if (root == null)
            return false;
        List<AccessibilityNodeInfo> matches =
                root.findAccessibilityNodeInfosByViewId(DOLPHIN_EXIT_ID);
        if (matches == null || matches.isEmpty())
            return false;
        return matches.get(0).performAction(AccessibilityNodeInfo.ACTION_CLICK);
    }

    private void returnToPegasus(final String contentPackage) {
        blankPreview();

        Intent pegasus = new Intent(Intent.ACTION_MAIN)
                .setComponent(PEGASUS_ACTIVITY)
                .addFlags(Intent.FLAG_ACTIVITY_NEW_TASK
                        | Intent.FLAG_ACTIVITY_REORDER_TO_FRONT
                        | Intent.FLAG_ACTIVITY_SINGLE_TOP);
        ActivityOptions options = ActivityOptions.makeBasic();
        options.setLaunchDisplayId(0);
        startActivity(pegasus, options.toBundle());

        // Do not call killBackgroundProcesses here. Besides discarding an
        // emulator's in-memory session, that could race its asynchronous SRAM
        // or autosave write. Android's normal task/LRU policy is the correct
        // memory manager for suspended games.
    }

    private boolean isClosableContentPackage(String packageName) {
        return packageName != null
                && !packageName.isEmpty()
                && !packageName.equals(PEGASUS_PACKAGE)
                && !packageName.equals(getPackageName())
                && !packageName.equals(PREVIEW_PACKAGE)
                && !packageName.equals("com.android.systemui")
                && !packageName.equals("com.android.settings")
                && !packageName.equals("com.android.launcher3")
                && !packageName.equals("com.odin.odinlauncher");
    }

    @Override
    public void onInterrupt() {
        stopHeld = false;
        holdActionTriggered = false;
        pressedContentPackage = "";
        ++stopGeneration;
        // No spoken or haptic feedback channel is used.
    }
}
